export default defineNuxtConfig({
  future: {
    compatibilityVersion: 4,
  },
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },
  app: {
    head: {
      title: 'Det 7:e Gunget | Blues och rock med glimt i ögat',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'description', content: 'Blues, rock, egna låtar och precis lagom mycket oväsen. Det 7:e Gunget från Ängelholm & Skåne.' },
        { name: 'theme-color', content: '#e2bd72' },
        { property: 'og:site_name', content: 'Det 7:e Gunget' },
        { property: 'og:title', content: 'Det 7:e Gunget | Blues och rock med glimt i ögat' },
        { property: 'og:description', content: 'Blues, rock, egna låtar och precis lagom mycket oväsen. Spelningar, musik och gött gung.' },
        { property: 'og:type', content: 'website' },
        { property: 'og:image', content: '/media/og/og-share.jpg' },
        { property: 'og:image:width', content: '1200' },
        { property: 'og:image:height', content: '630' },
        { property: 'og:image:alt', content: 'Det 7:e Gunget - Blues & Rock \'n\' Roll' },
        { name: 'twitter:card', content: 'summary_large_image' },
        { name: 'twitter:title', content: 'Det 7:e Gunget | Blues och rock med glimt i ögat' },
        { name: 'twitter:description', content: 'Blues, rock, egna låtar och precis lagom mycket oväsen. Se gig och lyssna i jukeboxen!' },
        { name: 'twitter:image', content: '/media/og/og-share.jpg' },
      ],
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
        { rel: 'icon', type: 'image/webp', href: '/media/brand/favicon.webp' },
        { rel: 'icon', type: 'image/webp', href: '/media/brand/Logotyp_mini.webp' },
        { rel: 'apple-touch-icon', href: '/media/brand/Logotyp_mini.webp' },
        { rel: 'manifest', href: '/site.webmanifest' },
      ],
    },
  },
  modules: [
    '@nuxtjs/tailwindcss',
    '@nuxt/image',
    '@nuxt/fonts',
    '@nuxtjs/i18n',
    '@nuxtjs/color-mode',
    '@nuxtjs/sitemap',
    '@nuxtjs/robots',
    '@nuxt/eslint',
  ],
  css: ['~/assets/css/main.css'],
  fonts: {
    families: [
      { name: 'Inter', provider: 'google' },
      { name: 'Corben', provider: 'google', weights: [700] },
      { name: 'Crete Round', provider: 'google', weights: [400], styles: ['normal', 'italic'] },
      { name: 'Rye', provider: 'google' },
      { name: 'Ultra', provider: 'google' },
    ],
  },
  i18n: {
    defaultLocale: 'sv',
    strategy: 'prefix_except_default',
    locales: [
      { code: 'sv', name: 'Svenska', file: 'sv.json' },
      { code: 'en', name: 'English', file: 'en.json' },
    ],
    langDir: '../i18n/locales',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected',
      redirectOn: 'root',
    },
  },
  colorMode: {
    preference: 'system',
    fallback: 'dark',
    dataValue: 'theme',
    classSuffix: '',
  },
  routeRules: {
    '/admin': { ssr: false },
    '/admin/**': { ssr: false },
  },
  site: {
    name: 'Det 7:e Gunget',
    description: 'Blues, rock och lagom mycket oväsen.',
  },
})